config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/quickwizard', as: 'rails_admin'
  resources :posts, except: :edit do
    resources :comments, only: [:create, :destroy]
    get 'my', on: :collection
    member do
      put 'like'
      put 'dislike'
    end
  end
  root to: 'posts#index'
  devise_for :users
  resources :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true, counter_cache: true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  validates :comment, presence: true
  validates :comment, length: {minimum: 5, maximum: 100}
end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  validates_presence_of :title
  belongs_to :user
  has_one :video, dependent: :destroy
  accepts_nested_attributes_for :video
  has_attached_file :meme, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :meme, :content_type => /\Aimage\/.*\Z/
  acts_as_commentable
  acts_as_votable

  def user_owns_it?
    user == current_user
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :moderator, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def to_s
    name
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :post
  validates_format_of :link, with: /(?:http\:\/\/)?(?:www\.)?(youtube|vimeo|dailymotion)\.(com|pl)/

  auto_html_for :link do
    html_escape
    image
    youtube(:width => 640, :height => 385, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :verify_authorized

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    authorize @comment
    if @comment.save
      redirect_to :back, notice: 'Comment was successfully created.'
    else
      redirect_to :back, alert: 'Comment wasn\'t saved'
    end
  end

  def destroy
    authorize @comment
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show]
  after_action :verify_authorized, except: [:index, :show]

  def index
    @posts = Post.includes(:video).page(params[:page]).per(10)
  end

  def my
    @posts = current_user.posts.includes(:video).page(params[:page]).per(15)
    authorize Post

    if @posts.any?
      render 'index'
    else
      render 'no_posts_for_this_user'
    end
  end

  def show
    @post = Post.includes(:video, :comments).find(params[:id])
    if current_user
      begin
        authorize @post, :destroy?
      rescue Pundit::NotAuthorizedError
        @am_i_even_allowed = false
      end

      @am_i_even_allowed = true unless defined? @am_i_even_allowed
    end
  end

  def new
    @post = Post.new
    @post.build_video
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    authorize @post
    if post_params[:meme].nil?
      @post.build_video(post_params[:video_attributes])
    else
      @post.video.delete unless @post.video.nil?
    end

    if @post.save
      redirect_to @post
    else
      redirect_to :back, alert: 'Post was NOT added.'
    end
  end

  def destroy
    authorize @post
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def like
    set_post
    authorize @post
    render 'like_dislike' if @post.upvote_by current_user
  end

  def dislike
    set_post
    authorize @post
    render 'like_dislike' if @post.downvote_by current_user
  end

  private


  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :meme, video_attributes: [:id, :link])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment row">
  <div class="row">
    <div class="col-xs-2">
      <div>
        <%#= [todo] edit/remove/report/etc. %>
      </div>
      
      Added by: <strong><%= comment.user %></strong>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 text-justify">
      <%= comment.comment %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for comment, url: post_comments_path(comment.commentable_id), method: 'post', :html => {class: 'form-inline'} do |f| %>
  <div class="form-group">
    <%= f.text_field :comment, class: 'form-control', :placeholder => 'comment (min 5 chars)' %>
    <%= f.submit 'wyslij', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'My Posts', my_posts_path %> </li>
  <li><%= link_to 'Add new Post', new_post_path %> </li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bombsite" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bombsite" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { class: 'form-inline' }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group">

      <div class="field memefield">
        <%= f.label :meme %><br>
        <%= f.file_field :meme, class: 'btn btn-default btn-file' %>
      </div>
      <%= f.fields_for :video do |v| %>
        <div class="field videofield">
          <%= v.label "Video link" %><br>
          <%= v.text_field :link, class: 'form-control' %>
        </div>
      <% end %>
      <div class="field clearboth">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit 'Wyślij', class: 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/posts/_post.html.erb
<div class="row">
<div class="col-md-2"> </div>
<div class="text-center col-md-8 post">
  <div class="row">
    <div class="col-md-4">
      <%= render 'voting', post: post %>
    </div>
    <div class="col-md-8 text-right">
      <h3><%= link_to post.title, post %></h3>
      Added by user: <b> <%= post.user %></b> |
      <%= link_to pluralize(post.comments.count, 'comment'), post %>
      <% if current_user %>
        <% if @am_i_even_allowed or post.user == current_user or current_user.admin? or current_user.moderator? %>
            | <%= link_to 'destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </div>
    <% if post.video.nil? %>
      <%= link_to image_tag(post.meme.url), post %>
    <% else %>
      <%= post.video.link_html %>
    <% end %>
  </div>
</div>
<div class="col-md-2"> </div>
</div>

app/views/posts/_voting.html.erb
<div class="row">
<div class="col-md-12 text-left voting"> 
  <% if current_user %>
    <div class="arrows">
      <%= link_to image_tag('arrow-up.png'), like_post_path(post), remote: true, method: :put %>
      <%= link_to image_tag('arrow-down.png'), dislike_post_path(post), remote: true, method: :put %>
    </div>
  <% end %>
  <div class="votes" id="post<%= post.id %>">
    <span class="votes_count"><%= (post.get_upvotes.size - post.get_downvotes.size).to_s %></span>
  </div>
</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render @posts %>

<div class="row">
  <div class="col-md-12 text-center">
  <%= paginate @posts %>
  </div>
</div>

app/views/posts/like_dislike.js.erb
$(document).ready(function() {
  $('#post<%= @post.id %> .votes_count').html('<%= @post.get_upvotes.size - @post.get_downvotes.size %>')
});

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <%= link_to 'Back', posts_path %>
    <h1>Add New Post</h1>
  </div>
</div>

<div class="col-md-3"></div>
<div class="col-md-6">
  <%= render 'form' %>
</div>
<div class="col-md-3"></div>

app/views/posts/no_posts_for_this_user.html.erb
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
  <h3>I believe you dont have any posts posted yet. Wanna try <%= link_to 'adding one?', new_post_path %> </h3>

</div>
<div class="col-md-2"></div>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 text-center">
    <%= render partial: 'comments/comment', collection: @post.comments %>
    <%= render 'comments/form', comment: @post.comments.new if @current_user %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>